# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0

version: "2"
run:
  modules-download-mode: vendor
  timeout: 3m0s # none by default in v2

issues:
  # '0' disables the following options
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    text:
      # Do not print lines of code with issue.
      print-issued-lines: false
