apiVersion: v1
kind: Service
metadata:
  name: {{.Host}}
  labels:
    service: {{.Host}}
spec:
  selector:
    app: {{.Host}}
  ports:
    - port: 3306
      name: dbport
      targetPort: dbport
      protocol: TCP