# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{.Host}}
  labels:
    service: {{.Host}}
spec:
  selector:
    app: {{.Host}}
  ports:
    - port: 3306
      name: dbport
      targetPort: dbport
      protocol: TCP